services:
  cassandra:
    image: cassandra:latest
    container_name: cassandraTABD
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TABD
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_STARTUP_TIMEOUT=300
      - CASSANDRA_CQLSH_TRY_SHORTEN=False

volumes:
  cassandra-data:
    driver: local
    driver_opts:
      type: "none"
      device: "./cassandra-data"
      o: "bind"
